=== google/osv.dev/go/internal/importer/schema_generated.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/ossf/osv-schema/main/validation/schema.json",
  "title": "Open Source Vulnerability",
  "description": "A schema for describing a vulnerability in an open source package. See also https://ossf.github.io/osv-schema/",
  "type": "object",
  "properties": {
    "schema_version": {
      "type": "string"
    },
    "id": {
      "$ref": "#/$defs/prefix"
    },
    "modified": {
      "$ref": "#/$defs/timestamp"
    },
    "published": {
      "$ref": "#/$defs/timestamp"
    },
    "withdrawn": {
      "$ref": "#/$defs/timestamp"
    },
    "aliases": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string"
      }
    },
    "related": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "upstream": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "summary": {
      "type": "string"
    },
    "details": {
      "type": "string"
    },
    "severity": {
      "$ref": "#/$defs/severity"
    },
    "affected": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "package": {
            "type": "object",
            "properties": {
              "ecosystem": {
                "$ref": "#/$defs/ecosystemWithSuffix"
              },
              "name": {
                "type": "string"
              },
              "purl": {
                "type": "string"
              }
            },
            "required": [
              "ecosystem",
              "name"
            ]
          },
          "severity": {
            "$ref": "#/$defs/severity"
          },
          "ranges": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "GIT",
                    "SEMVER",
                    "ECOSYSTEM"
                  ]
                },
                "repo": {
                  "type": "string"
                },
                "events": {
                  "title": "events must contain an introduced object and may contain fixed, last_affected or limit objects",
                  "type": "array",
                  "contains": {
                    "required": [
                      "introduced"
                    ]
                  },
                  "items": {
                    "type": "object",
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "introduced": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "introduced"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "fixed": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "fixed"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "last_affected": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "last_affected"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "limit": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "limit"
                        ]
                      }
                    ]
                  },
                  "minItems": 1
                },
                "database_specific": {
                  "type": "object"
                }
              },
              "allOf": [
                {
                  "title": "GIT ranges require a repo",
                  "if": {
                    "properties": {
                      "type": {
                        "const": "GIT"
                      }
                    }
                  },
                  "then": {
                    "required": [
                      "repo"
                    ]
                  }
                },
                {
                  "title": "last_affected and fixed events are mutually exclusive",
                  "if": {
                    "properties": {
                      "events": {
                        "contains": {
                          "required": [
                            "last_affected"
                          ]
                        }
                      }
                    }
                  },
                  "then": {
                    "not": {
                      "properties": {
                        "events": {
                          "contains": {
                            "required": [
                              "fixed"
                            ]
                          }
                        }
                      }
                    }
                  }
                }
              ],
              "required": [
                "type",
                "events"
              ]
            }
          },
          "versions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "ecosystem_specific": {
            "type": "object"
          },
          "database_specific": {
            "type": "object"
          }
        }
      }
    },
    "references": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "ADVISORY",
              "ARTICLE",
              "DETECTION",
              "DISCUSSION",
              "REPORT",
              "FIX",
              "INTRODUCED",
              "GIT",
              "PACKAGE",
              "EVIDENCE",
              "WEB"
            ]
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "type",
          "url"
        ]
      }
    },
    "credits": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "contact": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "type": {
            "type": "string",
            "enum": [
              "FINDER",
              "REPORTER",
              "ANALYST",
              "COORDINATOR",
              "REMEDIATION_DEVELOPER",
              "REMEDIATION_REVIEWER",
              "REMEDIATION_VERIFIER",
              "TOOL",
              "SPONSOR",
              "OTHER"
            ]
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "database_specific": {
      "type": "object"
    }
  },
  "required": [
    "id",
    "modified"
  ],
  "allOf": [
    {
      "if": {
        "required": [
          "severity"
        ]
      },
      "then": {
        "properties": {
          "affected": {
            "items": {
              "properties": {
                "severity": {
                  "type": "null"
                }
              }
            }
          }
        }
      }
    }
  ],
  "$defs": {
    "ecosystemName": {
      "type": "string",
      "title": "Currently supported ecosystems",
      "description": "These ecosystems are also documented at https://ossf.github.io/osv-schema/#affectedpackage-field",
      "enum": [
        "AlmaLinux",
        "Alpaquita",
        "Alpine",
        "Android",
        "Azure Linux",
        "BellSoft Hardened Containers",
        "Bioconductor",
        "Bitnami",
        "Chainguard",
        "CleanStart",
        "ConanCenter",
        "CRAN",
        "crates.io",
        "Debian",
        "Docker Hardened Images",
        "Echo",
        "FreeBSD",
        "GHC",
        "GitHub Actions",
        "Go",
        "Hackage",
        "Hex",
        "Julia",
        "Kubernetes",
        "Linux",
        "Mageia",
        "Maven",
        "MinimOS",
        "npm",
        "NuGet",
        "opam",
        "openEuler",
        "openSUSE",
        "OSS-Fuzz",
        "Packagist",
        "Photon OS",
        "Pub",
        "PyPI",
        "Red Hat",
        "Rocky Linux",
        "Root",
        "RubyGems",
        "SUSE",
        "SwiftURL",
        "Ubuntu",
        "VSCode",
        "Wolfi"
      ]
    },
    "ecosystemSuffix": {
      "type": "string",
      "pattern": ":.+"
    },
    "ecosystemWithSuffix": {
      "type": "string",
      "title": "Currently supported ecosystems",
      "description": "These ecosystems are also documented at https://ossf.github.io/osv-schema/#affectedpackage-field",
      "pattern": "^(AlmaLinux|Alpaquita|Alpine|Android|Azure Linux|BellSoft Hardened Containers|Bioconductor|Bitnami|Chainguard|CleanStart|ConanCenter|CRAN|crates\\.io|Debian|Docker Hardened Images|Echo|FreeBSD|GHC|GitHub Actions|Go|Hackage|Hex|Julia|Kubernetes|Linux|Mageia|Maven|MinimOS|npm|NuGet|opam|openEuler|openSUSE|OSS-Fuzz|Packagist|Photon OS|Pub|PyPI|Red Hat|Rocky Linux|Root|RubyGems|SUSE|SwiftURL|Ubuntu|VSCode|Wolfi|GIT)(:.+)?$"
    },
    "prefix": {
      "type": "string",
      "title": "Currently supported home database identifier prefixes",
      "description": "These home databases are also documented at https://ossf.github.io/osv-schema/#id-modified-fields",
      "pattern": "^(x_|(ASB-A|PUB-A|ALPINE|ALSA|ALBA|ALEA|AZL|BELL|BIT|CGA|CLEANSTART|CURL|CVE|DEBIAN|DHI|DRUPAL|DSA|DLA|ELA|DTSA|ECHO|EEF|FreeBSD|GHSA|GO|GSD|HSEC|JLSEC|KUBE|LBSEC|LSN|MAL|MINI|MGASA|OESA|OSEC|OSV|openSUSE-SU|PHSA|PSF|PYSEC|RHBA|RHEA|RHSA|RLSA|RXSA|RSEC|ROOT|RUSTSEC|SUSE-[SRFO]U|UBUNTU|USN|V8)-)"
    },
    "severity": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "CVSS_V2",
              "CVSS_V3",
              "CVSS_V4",
              "Ubuntu"
            ]
          },
          "score": {
            "type": "string"
          }
        },
        "allOf": [
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V2"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^((AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))/)*(AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V3"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^CVSS:3[.][01]/((AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])/)*(AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V4"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^CVSS:4[.]0/AV:[NALP]/AC:[LH]/AT:[NP]/PR:[NLH]/UI:[NPA]/VC:[HLN]/VI:[HLN]/VA:[HLN]/SC:[HLN]/SI:[HLN]/SA:[HLN](/E:[XAPU])?(/CR:[XHML])?(/IR:[XHML])?(/AR:[XHML])?(/MAV:[XNALP])?(/MAC:[XLH])?(/MAT:[XNP])?(/MPR:[XNLH])?(/MUI:[XNPA])?(/MVC:[XNLH])?(/MVI:[XNLH])?(/MVA:[XNLH])?(/MSC:[XNLH])?(/MSI:[XNLHS])?(/MSA:[XNLHS])?(/S:[XNP])?(/AU:[XNY])?(/R:[XAUI])?(/V:[XDC])?(/RE:[XLMH])?(/U:(X|Clear|Green|Amber|Red))?$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "Ubuntu"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "enum": [
                    "negligible",
                    "low",
                    "medium",
                    "high",
                    "critical"
                  ]
                }
              }
            }
          }
        ],
        "required": [
          "type",
          "score"
        ]
      }
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z"
    }
  },
  "additionalProperties": false
}

=== google/osv.dev/vulnfeeds/cmd/combine-to-osv/cve5/redhat/CVE-2023-1055.json
{
  "affected": [
    {}
  ],
  "database_specific": {
    "cna_assigner": "redhat",
    "cwe_ids": [
      "CWE-200"
    ],
    "osv_generated_from": "unknown",
    "unresolved_ranges": [
      {
        "metadata": {
          "source": "AFFECTED_FIELD"
        },
        "versions": [
          {
            "last_affected": "11 and 12"
          }
        ]
      }
    ]
  },
  "details": "A flaw was found in RHDS 11 and RHDS 12. While browsing entries LDAP tries to decode the userPassword attribute instead of the userCertificate attribute which could lead into sensitive information leaked. An attacker with a local account where the cockpit-389-ds is running can list the processes and display the hashed passwords. The highest threat from this vulnerability is to data confidentiality.",
  "id": "CVE-2023-1055",
  "modified": "2025-03-11T14:02:59.854Z",
  "published": "2023-02-27T00:00:00Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2173517#c0"
    },
    {
      "type": "ADVISORY",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MZOYQ5TCV6ZEPMDV4CSLK3KINAAO4SRI/"
    },
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-1055"
    }
  ],
  "schema_version": "1.7.3"
}

=== google/osv.dev/gcp/workers/importer/testdata/expected.json
{"id": "OSV-2017-134", "summary": "Heap-buffer-overflow in cdf_file_property_info", "details": "OSS-Fuzz report: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1064\n\nCrash type: Heap-buffer-overflow READ 1\nCrash state:\ncdf_file_property_info\ncdf_file_summary_info\ncdf_check_summary_info\n", "modified": "2021-01-01T00:00:00Z", "published": "2021-01-15T00:00:24.559102Z", "references": [{"type": "REPORT", "url": "https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1064"}], "affected": [{"package": {"name": "file", "ecosystem": "OSS-Fuzz", "purl": "pkg:generic/file"}, "ranges": [{"type": "GIT", "repo": "https://github.com/file/file.git", "events": [{"introduced": "17ee4cf670c363de8d2ea4a4897d7a699837873f"}, {"fixed": "19ccebafb7663c422c714e0c67fa4775abf91c43"}]}], "versions": ["FILE5_29", "FILE5_30"], "ecosystem_specific": {"severity": "MEDIUM"}}]}

=== google/osv.dev/vulnfeeds/cmd/ids/testdata/TEST-2026-21.json
{
  "id": "TEST-2026-21",
  "published": "2026-01-02T00:00:00Z",
  "modified": "2026-01-02T00:00:00Z",
  "summary": "A vulnerability",
  "details": "Blah blah blah\nBlah\n",
  "affected": [
    {
      "package": {
        "name": "blah.com/package",
        "ecosystem": "Go"
      },
      "ranges": [
        {
          "type": "GIT",
          "repo": "https://osv-test/repo/url",
          "events": [
            {
              "introduced": "eefe8ec3f1f90d0e684890e810f3f21e8500a4cd"
            },
            {
              "fixed": "8d8242f545e9cec3e6d0d2e3f5bde8be1c659735"
            }
          ]
        }
      ],
      "versions": [
        "branch-v0.1.1"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://ref.com/ref"
    }
  ],
  "database_specific": {
    "specific": 1337
  },
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L"
    }
  ],
  "credits": [
    {
      "name": "Foo bar",
      "contact": [
        "mailto:foo@bar.com"
      ]
    }
  ]
}

=== google/osv.dev/gcp/workers/worker/testdata/CVE-2022-27449.json
{
  "id": "CVE-2022-27449",
  "details": "MariaDB Server v10.9 and below was discovered to contain a segmentation fault via the component sql/item_func.cc:148.",
  "affected": [
    {
      "package": {
        "name": "mariadb",
        "ecosystem": "Alpine:v3.12",
        "purl": "pkg:alpine/mariadb"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "10.4.25-r0"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "name": "mariadb",
        "ecosystem": "Alpine:v3.13",
        "purl": "pkg:alpine/mariadb"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "10.5.16-r0"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "name": "mariadb",
        "ecosystem": "Alpine:v3.14",
        "purl": "pkg:alpine/mariadb"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "10.5.16-r0"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "name": "mariadb",
        "ecosystem": "Alpine:v3.15",
        "purl": "pkg:alpine/mariadb"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "10.6.8-r0"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "name": "mariadb",
        "ecosystem": "Alpine:v3.16",
        "purl": "pkg:alpine/mariadb"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "10.6.8-r0"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "EVIDENCE",
      "url": "https://jira.mariadb.org/browse/MDEV-28089"
    },
    {
      "type": "REPORT",
      "url": "https://jira.mariadb.org/browse/MDEV-28089"
    },
    {
      "type": "FIX",
      "url": "https://jira.mariadb.org/browse/MDEV-28089"
    },
    {
      "type": "WEB",
      "url": "https://jira.mariadb.org/browse/MDEV-28089"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.netapp.com/advisory/ntap-20220526-0006/"
    },
    {
      "type": "ARTICLE",
      "url": "https://lists.debian.org/debian-lts-announce/2022/09/msg00023.html"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2022/09/msg00023.html"
    }
  ],
  "modified": "2022-10-07T18:59:00Z",
  "published": "2022-04-14T13:15:00Z"
}

=== google/osv.dev/vulnfeeds/cmd/combine-to-osv/cve5/redhat/CVE-2018-14618.json
{
  "affected": [
    {}
  ],
  "database_specific": {
    "cna_assigner": "redhat",
    "cwe_ids": [
      "CWE-122",
      "CWE-131"
    ],
    "osv_generated_from": "unknown",
    "unresolved_ranges": [
      {
        "metadata": {
          "source": "AFFECTED_FIELD"
        },
        "versions": [
          {
            "last_affected": "7.61.1"
          }
        ]
      },
      {
        "metadata": {
          "source": "DESCRIPTION"
        },
        "versions": [
          {
            "fixed": "7.61.1"
          }
        ]
      }
    ]
  },
  "details": "curl before version 7.61.1 is vulnerable to a buffer overrun in the NTLM authentication code. The internal function Curl_ntlm_core_mk_nt_hash multiplies the length of the password by two (SUM) to figure out how large temporary storage area to allocate from the heap. The length value is then subsequently used to iterate over the password and generate output into the allocated storage buffer. On systems with a 32 bit size_t, the math to calculate SUM triggers an integer overflow when the password length exceeds 2GB (2^31 bytes). This integer overflow usually causes a very small buffer to actually get allocated instead of the intended very huge one, making the use of that buffer end up in a heap buffer overflow. (This bug is almost identical to CVE-2017-8816.)",
  "id": "CVE-2018-14618",
  "modified": "2024-08-05T09:29:51.906Z",
  "published": "2018-09-05T19:00:00Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "http://www.securitytracker.com/id/1041605"
    },
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/errata/RHSA-2018:3558"
    },
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/errata/RHSA-2019:1880"
    },
    {
      "type": "REPORT",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14618"
    },
    {
      "type": "WEB",
      "url": "https://cert-portal.siemens.com/productcert/pdf/ssa-436177.pdf"
    },
    {
      "type": "WEB",
      "url": "https://curl.haxx.se/docs/CVE-2018-14618.html"
    },
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-14618"
    },
    {
      "type": "WEB",
      "url": "https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2018-0014"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.gentoo.org/glsa/201903-03"
    },
    {
      "type": "ADVISORY",
      "url": "https://usn.ubuntu.com/3765-1/"
    },
    {
      "type": "ADVISORY",
      "url": "https://usn.ubuntu.com/3765-2/"
    },
    {
      "type": "ADVISORY",
      "url": "https://www.debian.org/security/2018/dsa-4286"
    }
  ],
  "schema_version": "1.7.3",
  "severity": [
    {
      "score": "CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "type": "CVSS_V3"
    }
  ]
}

=== google/osv.dev/vulnfeeds/cmd/combine-to-osv/nvd/haxx/libcurl/CVE-2018-14618.json
{
  "affected": [
    {
      "ranges": [
        {
          "database_specific": {
            "cpe": [
              "cpe:2.3:a:haxx:libcurl:*:*:*:*:*:*:*:*",
              "cpe:2.3:o:redhat:enterprise_linux:7.5:*:*:*:*:*:*:*",
              "cpe:2.3:o:redhat:enterprise_linux:7.6:*:*:*:*:*:*:*"
            ],
            "source": "CPE_FIELD",
            "versions": [
              {
                "introduced": "0"
              },
              {
                "fixed": "7.61.1"
              },
              {
                "last_affected": "7.5"
              },
              {
                "last_affected": "7.6"
              }
            ]
          },
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "432eb5f5c254ee8383b2522ce597c9219877923e"
            },
            {
              "last_affected": "52707f959058c148c8a5ef4e81d0599780a1c014"
            },
            {
              "last_affected": "ac98c73b04aec60683ec2094f3c311485f08d6ab"
            }
          ],
          "repo": "https://github.com/curl/curl",
          "type": "GIT"
        }
      ]
    }
  ],
  "database_specific": {
    "unresolved_ranges": [
      {
        "metadata": {
          "cpes": [
            "cpe:2.3:o:canonical:ubuntu_linux:12.04:*:*:*:esm:*:*:*",
            "cpe:2.3:o:canonical:ubuntu_linux:14.04:*:*:*:lts:*:*:*",
            "cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:*",
            "cpe:2.3:o:canonical:ubuntu_linux:18.04:*:*:*:lts:*:*:*",
            "cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*",
            "cpe:2.3:o:redhat:enterprise_linux:6.0:*:*:*:*:*:*:*",
            "cpe:2.3:o:redhat:enterprise_linux:7.0:*:*:*:*:*:*:*",
            "cpe:2.3:o:redhat:enterprise_linux:7.4:*:*:*:*:*:*:*"
          ],
          "source": "CPE_FIELD"
        },
        "versions": [
          {
            "last_affected": "12.04"
          },
          {
            "last_affected": "14.04"
          },
          {
            "last_affected": "16.04"
          },
          {
            "last_affected": "18.04"
          },
          {
            "last_affected": "9.0"
          },
          {
            "last_affected": "6.0"
          },
          {
            "last_affected": "7.0"
          },
          {
            "last_affected": "7.4"
          }
        ]
      }
    ]
  },
  "details": "curl before version 7.61.1 is vulnerable to a buffer overrun in the NTLM authentication code. The internal function Curl_ntlm_core_mk_nt_hash multiplies the length of the password by two (SUM) to figure out how large temporary storage area to allocate from the heap. The length value is then subsequently used to iterate over the password and generate output into the allocated storage buffer. On systems with a 32 bit size_t, the math to calculate SUM triggers an integer overflow when the password length exceeds 2GB (2^31 bytes). This integer overflow usually causes a very small buffer to actually get allocated instead of the intended very huge one, making the use of that buffer end up in a heap buffer overflow. (This bug is almost identical to CVE-2017-8816.)",
  "id": "CVE-2018-14618",
  "modified": "2024-11-21T03:49:26.003Z",
  "published": "2018-09-05T19:29:00.420Z",
  "references": [
    {
      "type": "WEB",
      "url": "https://cert-portal.siemens.com/productcert/pdf/ssa-436177.pdf"
    },
    {
      "type": "ADVISORY",
      "url": "http://www.securitytracker.com/id/1041605"
    },
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/errata/RHSA-2018:3558"
    },
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/errata/RHSA-2019:1880"
    },
    {
      "type": "ADVISORY",
      "url": "https://curl.haxx.se/docs/CVE-2018-14618.html"
    },
    {
      "type": "ADVISORY",
      "url": "https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2018-0014"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.gentoo.org/glsa/201903-03"
    },
    {
      "type": "ADVISORY",
      "url": "https://usn.ubuntu.com/3765-1/"
    },
    {
      "type": "ADVISORY",
      "url": "https://usn.ubuntu.com/3765-2/"
    },
    {
      "type": "ADVISORY",
      "url": "https://www.debian.org/security/2018/dsa-4286"
    },
    {
      "type": "REPORT",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14618"
    }
  ],
  "severity": [
    {
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "type": "CVSS_V3"
    }
  ]
}
